# Generated by Django 3.2.7 on 2021-10-04 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0003_alter_students_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
