# Generated by Django 3.2.7 on 2021-10-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0004_alter_students_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='id',
            new_name='unique_id',
        ),
    ]
