# Generated by Django 3.2.7 on 2021-10-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0005_rename_id_students_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
