# Generated by Django 3.2.7 on 2021-10-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0006_students_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_image',
            field=models.ImageField(blank=True, default='default_student.jpg', null=True, upload_to=''),
        ),
    ]
